### ISSUE TITLE
buzz-notify tries to install git hooks

### ISSUE THREAD

**Issue by qwerty287** [roberthgnz/buzz-notify#21]
Hello,
every time I install my project which uses buzz-notify, the [postinstall script](https://github.com/eliutdev/buzz-notify/blob/69e11d4d5ce0f6ec53e23b1b1228780b418401cc/package.json#L20) runs. This seems to be some dev script, but my project uses buzz-notify as dependency and I don't want to develop it. It would be good to remove this script or only run it if you directly have this project installed.

**Comment by eliutdev** [comment]
Hi @qwerty287 thanks for reporting this bug, it has been fixed. Make sure you have version 2.5.5 installed
